/* ═══════════════════════════════════════════════════════════
   Podcast Database — types + mock data (40 podcasts).
   Replace MOCK_PODCASTS with GET /api/podcasts when backend is live.
   All filtering, sorting, and display logic reads from these types.
   ═══════════════════════════════════════════════════════════ */

export type HostActivity      = "weekly" | "biweekly" | "monthly"
export type GuestAcceptance   = "open" | "selective"
export type VisibilityTier    = "very-high" | "high" | "medium" | "growing"
export type PodcastBadge      = "trending" | "high-engagement" | "fast-growing" | "ai-recommended"
export type ActivityStatus    = "active" | "hiatus" | "inactive"

export interface DiscoveryPodcast {
  // Identifiers
  id:                  string
  // Core info
  name:                string
  host:                string
  description:         string
  categories:          string[]
  subcategory?:        string
  // Platform links (backend will provide real URLs)
  website:             string
  podcastUrl:          string
  appleUrl:            string
  spotifyUrl:          string
  // Audience
  audienceType:        string          // descriptive: "Entrepreneurs & Founders"
  audienceSize:        number          // thousands (e.g. 45 = 45K)
  estimatedReach:      string          // formatted: "180K", "2.4M"
  // Podcast stats
  episodeCount:        number
  hostActivity:        HostActivity
  activityStatus:      ActivityStatus
  // Match signals
  matchScore:          number          // 0–100 placeholder
  audienceAlignment:   number          // 0–100
  guestFriendlyScore:  number          // 0–100
  guestAcceptance:     GuestAcceptance
  visibilityPotential: VisibilityTier
  badges:              PodcastBadge[]
  // Display
  coverIndex:          number          // 0–5 → COVER_GRADIENTS
  saved:               boolean
}

export interface DiscoveryFilters {
  categories:          string[]
  audienceSize:        string          // "any" | "<10k" | "10-50k" | "50-100k" | "100k+"
  hostActivity:        string          // "any" | "weekly" | "biweekly" | "monthly"
  guestAcceptance:     string          // "any" | "open" | "selective"
  activityStatus:      string          // "any" | "active" | "hiatus" | "inactive"
  minMatch:            number          // 0 | 70 | 80 | 85 | 90
  guestFriendlyMin:    number          // 0 | 60 | 75 | 85 | 90
  visibilityPotential: string          // "any" | "very-high" | "high" | "medium" | "growing"
}

export const DEFAULT_FILTERS: DiscoveryFilters = {
  categories:          [],
  audienceSize:        "any",
  hostActivity:        "any",
  guestAcceptance:     "any",
  activityStatus:      "any",
  minMatch:            0,
  guestFriendlyMin:    0,
  visibilityPotential: "any",
}

export const COVER_GRADIENTS = [
  "linear-gradient(135deg, oklch(0.58 0.220 255), oklch(0.70 0.160 200))",
  "linear-gradient(135deg, oklch(0.55 0.180 83),  oklch(0.78 0.150 83))",
  "linear-gradient(135deg, oklch(0.52 0.180 290), oklch(0.58 0.220 255))",
  "linear-gradient(135deg, oklch(0.48 0.160 160), oklch(0.65 0.160 200))",
  "linear-gradient(135deg, oklch(0.60 0.200 30),  oklch(0.52 0.180 290))",
  "linear-gradient(135deg, oklch(0.42 0.200 280), oklch(0.58 0.220 255))",
] as const

export const ALL_CATEGORIES = [
  "Business",
  "Entrepreneurship",
  "Leadership",
  "Technology",
  "Personal Development",
  "Health & Wellness",
  "Faith",
  "Marketing",
  "Mindset",
  "Finance & Investing",
  "Women in Business",
  "Education",
  "Spirituality",
  "Science",
  "Society & Culture",
  "Sports & Performance",
  "Parenting",
]

export const MOCK_PODCASTS: DiscoveryPodcast[] = [
  // ── 1 ──────────────────────────────────────────────────────────
  {
    id: "1",
    name: "The Founder's Mindset",
    host: "David Chen",
    description: "Weekly conversations with founders about building resilient businesses and mental strength in the startup journey.",
    categories: ["Entrepreneurship", "Business", "Mindset"],
    subcategory: "Founder Stories",
    website: "foundersmindset.co",
    podcastUrl: "https://foundersmindset.co/listen",
    appleUrl: "https://podcasts.apple.com/podcast/founders-mindset",
    spotifyUrl: "https://open.spotify.com/show/foundersmindset",
    audienceType: "Entrepreneurs & Founders",
    audienceSize: 45,
    estimatedReach: "180K",
    episodeCount: 218,
    matchScore: 95,
    audienceAlignment: 92,
    guestFriendlyScore: 94,
    hostActivity: "weekly",
    guestAcceptance: "open",
    activityStatus: "active",
    visibilityPotential: "high",
    badges: ["ai-recommended", "trending"],
    coverIndex: 0,
    saved: false,
  },
  // ── 2 ──────────────────────────────────────────────────────────
  {
    id: "2",
    name: "Leadership Lab",
    host: "Sarah Mitchell",
    description: "Evidence-based leadership strategies for modern executives and team builders navigating complex organizations.",
    categories: ["Leadership", "Business"],
    subcategory: "Executive Leadership",
    website: "leadershiplab.io",
    podcastUrl: "https://leadershiplab.io/podcast",
    appleUrl: "https://podcasts.apple.com/podcast/leadership-lab",
    spotifyUrl: "https://open.spotify.com/show/leadershiplab",
    audienceType: "Executives & Managers",
    audienceSize: 128,
    estimatedReach: "640K",
    episodeCount: 312,
    matchScore: 89,
    audienceAlignment: 85,
    guestFriendlyScore: 72,
    hostActivity: "weekly",
    guestAcceptance: "selective",
    activityStatus: "active",
    visibilityPotential: "high",
    badges: ["high-engagement"],
    coverIndex: 1,
    saved: true,
  },
  // ── 3 ──────────────────────────────────────────────────────────
  {
    id: "3",
    name: "Tech Startup Insider",
    host: "James Park",
    description: "Real talk from tech founders about product-market fit, AI-driven growth, and what it actually takes to scale.",
    categories: ["Technology", "Entrepreneurship"],
    subcategory: "Tech Founders",
    website: "techstartupinsider.com",
    podcastUrl: "https://techstartupinsider.com/listen",
    appleUrl: "https://podcasts.apple.com/podcast/tech-startup-insider",
    spotifyUrl: "https://open.spotify.com/show/techstartupinsider",
    audienceType: "Tech Founders & Builders",
    audienceSize: 67,
    estimatedReach: "335K",
    episodeCount: 184,
    matchScore: 96,
    audienceAlignment: 94,
    guestFriendlyScore: 91,
    hostActivity: "weekly",
    guestAcceptance: "open",
    activityStatus: "active",
    visibilityPotential: "very-high",
    badges: ["ai-recommended", "fast-growing"],
    coverIndex: 2,
    saved: false,
  },
  // ── 4 ──────────────────────────────────────────────────────────
  {
    id: "4",
    name: "Mindset Mastery",
    host: "Dr. Lisa Torres",
    description: "Deep psychology and neuroscience-backed conversations for peak mental performance and lasting personal growth.",
    categories: ["Personal Development", "Mindset"],
    subcategory: "Performance Psychology",
    website: "mindsetmastery.fm",
    podcastUrl: "https://mindsetmastery.fm/listen",
    appleUrl: "https://podcasts.apple.com/podcast/mindset-mastery",
    spotifyUrl: "https://open.spotify.com/show/mindsetmastery",
    audienceType: "High Performers & Coaches",
    audienceSize: 23,
    estimatedReach: "92K",
    episodeCount: 147,
    matchScore: 88,
    audienceAlignment: 88,
    guestFriendlyScore: 86,
    hostActivity: "biweekly",
    guestAcceptance: "open",
    activityStatus: "active",
    visibilityPotential: "growing",
    badges: [],
    coverIndex: 3,
    saved: false,
  },
  // ── 5 ──────────────────────────────────────────────────────────
  {
    id: "5",
    name: "The Creator Economy",
    host: "Marco Rivera",
    description: "Monetization, audience building, and creative business models for independent creators building in public.",
    categories: ["Business", "Marketing"],
    subcategory: "Creator Business",
    website: "creatoreconomypod.com",
    podcastUrl: "https://creatoreconomypod.com/listen",
    appleUrl: "https://podcasts.apple.com/podcast/creator-economy",
    spotifyUrl: "https://open.spotify.com/show/creatoreconomy",
    audienceType: "Content Creators & Solopreneurs",
    audienceSize: 92,
    estimatedReach: "460K",
    episodeCount: 253,
    matchScore: 84,
    audienceAlignment: 82,
    guestFriendlyScore: 75,
    hostActivity: "weekly",
    guestAcceptance: "selective",
    activityStatus: "active",
    visibilityPotential: "high",
    badges: ["trending"],
    coverIndex: 4,
    saved: false,
  },
  // ── 6 ──────────────────────────────────────────────────────────
  {
    id: "6",
    name: "Faith & Business",
    host: "Marcus Webb",
    description: "Where faith meets entrepreneurship — purpose-driven business conversations that honor your values and your vision.",
    categories: ["Faith", "Business", "Entrepreneurship"],
    subcategory: "Faith-Driven Business",
    website: "faithandbusiness.com",
    podcastUrl: "https://faithandbusiness.com/podcast",
    appleUrl: "https://podcasts.apple.com/podcast/faith-and-business",
    spotifyUrl: "https://open.spotify.com/show/faithandbusiness",
    audienceType: "Faith-Based Entrepreneurs",
    audienceSize: 34,
    estimatedReach: "136K",
    episodeCount: 167,
    matchScore: 91,
    audienceAlignment: 89,
    guestFriendlyScore: 93,
    hostActivity: "weekly",
    guestAcceptance: "open",
    activityStatus: "active",
    visibilityPotential: "medium",
    badges: ["ai-recommended"],
    coverIndex: 5,
    saved: false,
  },
  // ── 7 ──────────────────────────────────────────────────────────
  {
    id: "7",
    name: "Women in Leadership",
    host: "Dr. Priya Nair",
    description: "Amplifying women's voices in executive spaces, boardrooms, and entrepreneurship with real stories and strategy.",
    categories: ["Leadership", "Women in Business"],
    subcategory: "Female Leadership",
    website: "womeninleadership.fm",
    podcastUrl: "https://womeninleadership.fm/listen",
    appleUrl: "https://podcasts.apple.com/podcast/women-in-leadership",
    spotifyUrl: "https://open.spotify.com/show/womeninleadership",
    audienceType: "Women Executives & Leaders",
    audienceSize: 78,
    estimatedReach: "390K",
    episodeCount: 201,
    matchScore: 87,
    audienceAlignment: 86,
    guestFriendlyScore: 89,
    hostActivity: "weekly",
    guestAcceptance: "open",
    activityStatus: "active",
    visibilityPotential: "high",
    badges: ["high-engagement", "trending"],
    coverIndex: 0,
    saved: false,
  },
  // ── 8 ──────────────────────────────────────────────────────────
  {
    id: "8",
    name: "Growth Hacking Decoded",
    host: "Alex Hoffman",
    description: "Tactical growth strategies, data-driven marketing frameworks, and viral product mechanics for B2B and B2C.",
    categories: ["Marketing", "Business"],
    subcategory: "Growth Marketing",
    website: "growthhackingdecoded.com",
    podcastUrl: "https://growthhackingdecoded.com/podcast",
    appleUrl: "https://podcasts.apple.com/podcast/growth-hacking-decoded",
    spotifyUrl: "https://open.spotify.com/show/growthhackingdecoded",
    audienceType: "Marketers & Growth Professionals",
    audienceSize: 41,
    estimatedReach: "164K",
    episodeCount: 189,
    matchScore: 83,
    audienceAlignment: 80,
    guestFriendlyScore: 68,
    hostActivity: "biweekly",
    guestAcceptance: "selective",
    activityStatus: "active",
    visibilityPotential: "medium",
    badges: [],
    coverIndex: 1,
    saved: false,
  },
  // ── 9 ──────────────────────────────────────────────────────────
  {
    id: "9",
    name: "Recovery Stories",
    host: "Emma Castillo",
    description: "Honest, healing conversations about addiction recovery, resilience, mental health, and building life after hardship.",
    categories: ["Health & Wellness", "Personal Development"],
    subcategory: "Mental Health & Recovery",
    website: "recoverystories.com",
    podcastUrl: "https://recoverystories.com/listen",
    appleUrl: "https://podcasts.apple.com/podcast/recovery-stories",
    spotifyUrl: "https://open.spotify.com/show/recoverystories",
    audienceType: "Recovery Community & Health Seekers",
    audienceSize: 19,
    estimatedReach: "76K",
    episodeCount: 112,
    matchScore: 92,
    audienceAlignment: 91,
    guestFriendlyScore: 96,
    hostActivity: "weekly",
    guestAcceptance: "open",
    activityStatus: "active",
    visibilityPotential: "growing",
    badges: ["ai-recommended", "fast-growing"],
    coverIndex: 2,
    saved: false,
  },
  // ── 10 ─────────────────────────────────────────────────────────
  {
    id: "10",
    name: "Bold Moves Podcast",
    host: "Ryan Carter",
    description: "Stories of calculated risk-taking, massive pivots, and building audacious businesses in uncertain markets.",
    categories: ["Entrepreneurship", "Business"],
    subcategory: "Business Risk & Strategy",
    website: "boldmovespodcast.com",
    podcastUrl: "https://boldmovespodcast.com/listen",
    appleUrl: "https://podcasts.apple.com/podcast/bold-moves",
    spotifyUrl: "https://open.spotify.com/show/boldmoves",
    audienceType: "Risk-Taking Entrepreneurs",
    audienceSize: 55,
    estimatedReach: "275K",
    episodeCount: 176,
    matchScore: 86,
    audienceAlignment: 84,
    guestFriendlyScore: 88,
    hostActivity: "weekly",
    guestAcceptance: "open",
    activityStatus: "active",
    visibilityPotential: "high",
    badges: ["trending"],
    coverIndex: 3,
    saved: false,
  },
  // ── 11 ─────────────────────────────────────────────────────────
  {
    id: "11",
    name: "The Resilience Project",
    host: "Dr. Michael Santos",
    description: "Building emotional resilience through adversity — real stories from leaders who broke and rebuilt stronger.",
    categories: ["Personal Development", "Health & Wellness", "Mindset"],
    subcategory: "Resilience & Adversity",
    website: "resilienceproject.fm",
    podcastUrl: "https://resilienceproject.fm/listen",
    appleUrl: "https://podcasts.apple.com/podcast/resilience-project",
    spotifyUrl: "https://open.spotify.com/show/resilienceproject",
    audienceType: "Leaders & High Performers",
    audienceSize: 31,
    estimatedReach: "124K",
    episodeCount: 143,
    matchScore: 90,
    audienceAlignment: 87,
    guestFriendlyScore: 85,
    hostActivity: "biweekly",
    guestAcceptance: "open",
    activityStatus: "active",
    visibilityPotential: "growing",
    badges: ["ai-recommended"],
    coverIndex: 4,
    saved: false,
  },
  // ── 12 ─────────────────────────────────────────────────────────
  {
    id: "12",
    name: "Future of Work",
    host: "Nina Yamamoto",
    description: "The evolving workplace — AI transformation, remote culture, and leadership in distributed, global teams.",
    categories: ["Technology", "Leadership", "Business"],
    subcategory: "Future Workplace",
    website: "futureofworkpod.com",
    podcastUrl: "https://futureofworkpod.com/listen",
    appleUrl: "https://podcasts.apple.com/podcast/future-of-work",
    spotifyUrl: "https://open.spotify.com/show/futureofwork",
    audienceType: "Business Leaders & HR Professionals",
    audienceSize: 63,
    estimatedReach: "315K",
    episodeCount: 224,
    matchScore: 85,
    audienceAlignment: 83,
    guestFriendlyScore: 71,
    hostActivity: "weekly",
    guestAcceptance: "selective",
    activityStatus: "active",
    visibilityPotential: "high",
    badges: ["high-engagement", "fast-growing"],
    coverIndex: 5,
    saved: false,
  },
  // ── 13 ─────────────────────────────────────────────────────────
  {
    id: "13",
    name: "The Bootstrapper",
    host: "Amy Lin",
    description: "No investors, no excuses — raw stories of founders building profitable companies on their own terms.",
    categories: ["Entrepreneurship", "Business"],
    subcategory: "Bootstrapped Business",
    website: "thebootstrapper.fm",
    podcastUrl: "https://thebootstrapper.fm/listen",
    appleUrl: "https://podcasts.apple.com/podcast/the-bootstrapper",
    spotifyUrl: "https://open.spotify.com/show/thebootstrapper",
    audienceType: "Bootstrapped Founders",
    audienceSize: 28,
    estimatedReach: "112K",
    episodeCount: 138,
    matchScore: 87,
    audienceAlignment: 85,
    guestFriendlyScore: 90,
    hostActivity: "weekly",
    guestAcceptance: "open",
    activityStatus: "active",
    visibilityPotential: "growing",
    badges: ["fast-growing"],
    coverIndex: 0,
    saved: false,
  },
  // ── 14 ─────────────────────────────────────────────────────────
  {
    id: "14",
    name: "Startup Secrets",
    host: "Kevin O'Brien",
    description: "The unfiltered playbook behind successful startups — from 0 to exit, with every messy detail in between.",
    categories: ["Entrepreneurship", "Business", "Technology"],
    subcategory: "Startup Strategy",
    website: "startupsecretspod.com",
    podcastUrl: "https://startupsecretspod.com/listen",
    appleUrl: "https://podcasts.apple.com/podcast/startup-secrets",
    spotifyUrl: "https://open.spotify.com/show/startupsecrets",
    audienceType: "Early-Stage Founders",
    audienceSize: 52,
    estimatedReach: "260K",
    episodeCount: 195,
    matchScore: 91,
    audienceAlignment: 89,
    guestFriendlyScore: 87,
    hostActivity: "weekly",
    guestAcceptance: "open",
    activityStatus: "active",
    visibilityPotential: "high",
    badges: ["ai-recommended", "trending"],
    coverIndex: 1,
    saved: false,
  },
  // ── 15 ─────────────────────────────────────────────────────────
  {
    id: "15",
    name: "Beyond the Pitch",
    host: "Natasha Okonkwo",
    description: "What happens after the fundraise — operating, scaling, and surviving as a VC-backed founder in a competitive market.",
    categories: ["Entrepreneurship", "Business"],
    subcategory: "VC-Backed Startups",
    website: "beyondthepitch.co",
    podcastUrl: "https://beyondthepitch.co/podcast",
    appleUrl: "https://podcasts.apple.com/podcast/beyond-the-pitch",
    spotifyUrl: "https://open.spotify.com/show/beyondthepitch",
    audienceType: "VC-Backed Founders & Investors",
    audienceSize: 84,
    estimatedReach: "420K",
    episodeCount: 267,
    matchScore: 88,
    audienceAlignment: 86,
    guestFriendlyScore: 76,
    hostActivity: "biweekly",
    guestAcceptance: "selective",
    activityStatus: "active",
    visibilityPotential: "high",
    badges: ["high-engagement"],
    coverIndex: 2,
    saved: false,
  },
  // ── 16 ─────────────────────────────────────────────────────────
  {
    id: "16",
    name: "AI Disrupted",
    host: "Sam Washington",
    description: "How artificial intelligence is reshaping industries, careers, and the human experience — for business leaders.",
    categories: ["Technology", "Business"],
    subcategory: "AI & Future Tech",
    website: "aidisrupted.com",
    podcastUrl: "https://aidisrupted.com/listen",
    appleUrl: "https://podcasts.apple.com/podcast/ai-disrupted",
    spotifyUrl: "https://open.spotify.com/show/aidisrupted",
    audienceType: "Tech Leaders & AI Adopters",
    audienceSize: 113,
    estimatedReach: "565K",
    episodeCount: 159,
    matchScore: 93,
    audienceAlignment: 91,
    guestFriendlyScore: 78,
    hostActivity: "weekly",
    guestAcceptance: "selective",
    activityStatus: "active",
    visibilityPotential: "very-high",
    badges: ["trending", "fast-growing"],
    coverIndex: 3,
    saved: false,
  },
  // ── 17 ─────────────────────────────────────────────────────────
  {
    id: "17",
    name: "Deep Tech Weekly",
    host: "Rachel Huang",
    description: "Frontier technology — biotech, quantum, robotics, and the breakthroughs transforming science and industry.",
    categories: ["Technology", "Science"],
    subcategory: "Frontier Technology",
    website: "deeptechweekly.fm",
    podcastUrl: "https://deeptechweekly.fm/listen",
    appleUrl: "https://podcasts.apple.com/podcast/deep-tech-weekly",
    spotifyUrl: "https://open.spotify.com/show/deeptechweekly",
    audienceType: "Scientists & Tech Professionals",
    audienceSize: 47,
    estimatedReach: "188K",
    episodeCount: 142,
    matchScore: 80,
    audienceAlignment: 78,
    guestFriendlyScore: 73,
    hostActivity: "weekly",
    guestAcceptance: "selective",
    activityStatus: "active",
    visibilityPotential: "medium",
    badges: [],
    coverIndex: 4,
    saved: false,
  },
  // ── 18 ─────────────────────────────────────────────────────────
  {
    id: "18",
    name: "The Executive Edge",
    host: "Thomas Brennan",
    description: "C-suite insights, board-level strategy, and the decision frameworks that define exceptional organizational leaders.",
    categories: ["Leadership", "Business"],
    subcategory: "C-Suite Strategy",
    website: "theexecutiveedge.com",
    podcastUrl: "https://theexecutiveedge.com/podcast",
    appleUrl: "https://podcasts.apple.com/podcast/executive-edge",
    spotifyUrl: "https://open.spotify.com/show/executiveedge",
    audienceType: "C-Suite Executives & Directors",
    audienceSize: 156,
    estimatedReach: "780K",
    episodeCount: 341,
    matchScore: 86,
    audienceAlignment: 83,
    guestFriendlyScore: 69,
    hostActivity: "weekly",
    guestAcceptance: "selective",
    activityStatus: "active",
    visibilityPotential: "high",
    badges: ["high-engagement"],
    coverIndex: 5,
    saved: false,
  },
  // ── 19 ─────────────────────────────────────────────────────────
  {
    id: "19",
    name: "Lead Forward",
    host: "Maya Johnson",
    description: "Inclusive leadership, team psychology, and the emotional intelligence skills that separate good from great leaders.",
    categories: ["Leadership", "Personal Development"],
    subcategory: "Inclusive Leadership",
    website: "leadforwardpod.com",
    podcastUrl: "https://leadforwardpod.com/listen",
    appleUrl: "https://podcasts.apple.com/podcast/lead-forward",
    spotifyUrl: "https://open.spotify.com/show/leadforward",
    audienceType: "Mid-Level Managers & Emerging Leaders",
    audienceSize: 38,
    estimatedReach: "152K",
    episodeCount: 121,
    matchScore: 84,
    audienceAlignment: 82,
    guestFriendlyScore: 91,
    hostActivity: "biweekly",
    guestAcceptance: "open",
    activityStatus: "active",
    visibilityPotential: "growing",
    badges: ["ai-recommended"],
    coverIndex: 0,
    saved: false,
  },
  // ── 20 ─────────────────────────────────────────────────────────
  {
    id: "20",
    name: "Level Up Daily",
    host: "Chris Park",
    description: "Short-form daily habits, routines, and mindset shifts for the ambitious professional who refuses to settle.",
    categories: ["Personal Development", "Mindset"],
    subcategory: "Daily Habits",
    website: "levelupdaily.co",
    podcastUrl: "https://levelupdaily.co/podcast",
    appleUrl: "https://podcasts.apple.com/podcast/level-up-daily",
    spotifyUrl: "https://open.spotify.com/show/levelupdaily",
    audienceType: "Ambitious Professionals",
    audienceSize: 210,
    estimatedReach: "1.05M",
    episodeCount: 412,
    matchScore: 82,
    audienceAlignment: 80,
    guestFriendlyScore: 64,
    hostActivity: "weekly",
    guestAcceptance: "selective",
    activityStatus: "active",
    visibilityPotential: "very-high",
    badges: ["trending", "fast-growing"],
    coverIndex: 1,
    saved: false,
  },
  // ── 21 ─────────────────────────────────────────────────────────
  {
    id: "21",
    name: "The Growth Equation",
    host: "Dr. Fatima Al-Hassan",
    description: "Research-backed frameworks for sustainable personal and professional growth — no hustle culture, just science.",
    categories: ["Personal Development", "Education"],
    subcategory: "Evidence-Based Growth",
    website: "growthequation.fm",
    podcastUrl: "https://growthequation.fm/listen",
    appleUrl: "https://podcasts.apple.com/podcast/growth-equation",
    spotifyUrl: "https://open.spotify.com/show/growthequation",
    audienceType: "Evidence-Driven Professionals",
    audienceSize: 29,
    estimatedReach: "116K",
    episodeCount: 98,
    matchScore: 89,
    audienceAlignment: 87,
    guestFriendlyScore: 88,
    hostActivity: "biweekly",
    guestAcceptance: "open",
    activityStatus: "active",
    visibilityPotential: "growing",
    badges: ["ai-recommended"],
    coverIndex: 2,
    saved: false,
  },
  // ── 22 ─────────────────────────────────────────────────────────
  {
    id: "22",
    name: "The Wellbeing Code",
    host: "Dr. Sarah Jenkins",
    description: "Integrative wellness — mental health, physical performance, and the science of thriving in high-pressure careers.",
    categories: ["Health & Wellness", "Personal Development"],
    subcategory: "Integrative Health",
    website: "wellbeingcode.com",
    podcastUrl: "https://wellbeingcode.com/listen",
    appleUrl: "https://podcasts.apple.com/podcast/wellbeing-code",
    spotifyUrl: "https://open.spotify.com/show/wellbeingcode",
    audienceType: "Health-Conscious Professionals",
    audienceSize: 61,
    estimatedReach: "305K",
    episodeCount: 189,
    matchScore: 91,
    audienceAlignment: 90,
    guestFriendlyScore: 92,
    hostActivity: "weekly",
    guestAcceptance: "open",
    activityStatus: "active",
    visibilityPotential: "high",
    badges: ["ai-recommended", "high-engagement"],
    coverIndex: 3,
    saved: false,
  },
  // ── 23 ─────────────────────────────────────────────────────────
  {
    id: "23",
    name: "Mind & Body Reset",
    host: "Marcus Grant",
    description: "Holistic approaches to burnout recovery, stress management, and rebuilding energy for sustained high performance.",
    categories: ["Health & Wellness", "Mindset"],
    subcategory: "Burnout & Recovery",
    website: "mindbodyreset.fm",
    podcastUrl: "https://mindbodyreset.fm/podcast",
    appleUrl: "https://podcasts.apple.com/podcast/mind-body-reset",
    spotifyUrl: "https://open.spotify.com/show/mindbodyreset",
    audienceType: "Burned-Out Professionals",
    audienceSize: 17,
    estimatedReach: "68K",
    episodeCount: 84,
    matchScore: 94,
    audienceAlignment: 93,
    guestFriendlyScore: 97,
    hostActivity: "biweekly",
    guestAcceptance: "open",
    activityStatus: "active",
    visibilityPotential: "growing",
    badges: ["ai-recommended", "fast-growing"],
    coverIndex: 4,
    saved: false,
  },
  // ── 24 ─────────────────────────────────────────────────────────
  {
    id: "24",
    name: "Spirit-Led Success",
    host: "Pastor Diana White",
    description: "Where divine purpose meets professional strategy — conversations for faith-led entrepreneurs and kingdom builders.",
    categories: ["Faith", "Entrepreneurship", "Spirituality"],
    subcategory: "Kingdom Business",
    website: "spiritledsuccess.com",
    podcastUrl: "https://spiritledsuccess.com/podcast",
    appleUrl: "https://podcasts.apple.com/podcast/spirit-led-success",
    spotifyUrl: "https://open.spotify.com/show/spiritledsuccess",
    audienceType: "Faith-Driven Entrepreneurs",
    audienceSize: 44,
    estimatedReach: "220K",
    episodeCount: 167,
    matchScore: 88,
    audienceAlignment: 86,
    guestFriendlyScore: 95,
    hostActivity: "weekly",
    guestAcceptance: "open",
    activityStatus: "active",
    visibilityPotential: "medium",
    badges: ["ai-recommended"],
    coverIndex: 5,
    saved: false,
  },
  // ── 25 ─────────────────────────────────────────────────────────
  {
    id: "25",
    name: "The Sacred Entrepreneur",
    host: "James O'Connor",
    description: "Integrating spiritual principles into everyday business decisions for entrepreneurs of all faith backgrounds.",
    categories: ["Spirituality", "Business"],
    subcategory: "Spiritual Business",
    website: "sacredentrepreneur.co",
    podcastUrl: "https://sacredentrepreneur.co/listen",
    appleUrl: "https://podcasts.apple.com/podcast/sacred-entrepreneur",
    spotifyUrl: "https://open.spotify.com/show/sacredentrepreneur",
    audienceType: "Spiritually Conscious Business Owners",
    audienceSize: 22,
    estimatedReach: "88K",
    episodeCount: 91,
    matchScore: 83,
    audienceAlignment: 81,
    guestFriendlyScore: 94,
    hostActivity: "biweekly",
    guestAcceptance: "open",
    activityStatus: "active",
    visibilityPotential: "growing",
    badges: [],
    coverIndex: 0,
    saved: false,
  },
  // ── 26 ─────────────────────────────────────────────────────────
  {
    id: "26",
    name: "Content That Converts",
    host: "Jessica Torres",
    description: "The psychology of persuasive content — storytelling, copywriting, and audience psychology for modern marketers.",
    categories: ["Marketing", "Business"],
    subcategory: "Content Marketing",
    website: "contentthatconverts.fm",
    podcastUrl: "https://contentthatconverts.fm/listen",
    appleUrl: "https://podcasts.apple.com/podcast/content-that-converts",
    spotifyUrl: "https://open.spotify.com/show/contentthatconverts",
    audienceType: "Marketers & Content Creators",
    audienceSize: 74,
    estimatedReach: "370K",
    episodeCount: 231,
    matchScore: 85,
    audienceAlignment: 83,
    guestFriendlyScore: 80,
    hostActivity: "weekly",
    guestAcceptance: "selective",
    activityStatus: "active",
    visibilityPotential: "high",
    badges: ["trending"],
    coverIndex: 1,
    saved: false,
  },
  // ── 27 ─────────────────────────────────────────────────────────
  {
    id: "27",
    name: "The Brand Builders",
    host: "Michael Kim",
    description: "Personal and corporate brand architecture — how to build authority, trust, and recognition in saturated markets.",
    categories: ["Marketing", "Business", "Entrepreneurship"],
    subcategory: "Brand Strategy",
    website: "thebrandbuilders.co",
    podcastUrl: "https://thebrandbuilders.co/podcast",
    appleUrl: "https://podcasts.apple.com/podcast/brand-builders",
    spotifyUrl: "https://open.spotify.com/show/brandbuilders",
    audienceType: "Entrepreneurs & Brand Builders",
    audienceSize: 58,
    estimatedReach: "290K",
    episodeCount: 183,
    matchScore: 87,
    audienceAlignment: 85,
    guestFriendlyScore: 77,
    hostActivity: "biweekly",
    guestAcceptance: "selective",
    activityStatus: "active",
    visibilityPotential: "high",
    badges: ["high-engagement"],
    coverIndex: 2,
    saved: false,
  },
  // ── 28 ─────────────────────────────────────────────────────────
  {
    id: "28",
    name: "The Wealth Blueprint",
    host: "David Morrison",
    description: "Building generational wealth through smart investing, financial systems, and the wealth mindset of the ultra-successful.",
    categories: ["Finance & Investing", "Business"],
    subcategory: "Wealth Building",
    website: "wealthblueprintpod.com",
    podcastUrl: "https://wealthblueprintpod.com/listen",
    appleUrl: "https://podcasts.apple.com/podcast/wealth-blueprint",
    spotifyUrl: "https://open.spotify.com/show/wealthblueprint",
    audienceType: "Wealth-Building Professionals",
    audienceSize: 97,
    estimatedReach: "485K",
    episodeCount: 278,
    matchScore: 84,
    audienceAlignment: 82,
    guestFriendlyScore: 74,
    hostActivity: "weekly",
    guestAcceptance: "selective",
    activityStatus: "active",
    visibilityPotential: "high",
    badges: ["trending"],
    coverIndex: 3,
    saved: false,
  },
  // ── 29 ─────────────────────────────────────────────────────────
  {
    id: "29",
    name: "Smart Money Moves",
    host: "Alicia Chang",
    description: "Practical personal finance and investing strategies for first-generation wealth builders and career-driven millennials.",
    categories: ["Finance & Investing", "Personal Development"],
    subcategory: "Personal Finance",
    website: "smartmoneymoves.fm",
    podcastUrl: "https://smartmoneymoves.fm/podcast",
    appleUrl: "https://podcasts.apple.com/podcast/smart-money-moves",
    spotifyUrl: "https://open.spotify.com/show/smartmoneymoves",
    audienceType: "First-Gen Wealth Builders",
    audienceSize: 143,
    estimatedReach: "715K",
    episodeCount: 324,
    matchScore: 81,
    audienceAlignment: 79,
    guestFriendlyScore: 83,
    hostActivity: "weekly",
    guestAcceptance: "open",
    activityStatus: "active",
    visibilityPotential: "very-high",
    badges: ["fast-growing", "trending"],
    coverIndex: 4,
    saved: false,
  },
  // ── 30 ─────────────────────────────────────────────────────────
  {
    id: "30",
    name: "The Financial Freedom Show",
    host: "Robert Anderson",
    description: "The path to financial independence — real estate, passive income, FIRE strategies, and escaping the 9-to-5.",
    categories: ["Finance & Investing", "Entrepreneurship"],
    subcategory: "Financial Independence",
    website: "financialfreedomshow.com",
    podcastUrl: "https://financialfreedomshow.com/listen",
    appleUrl: "https://podcasts.apple.com/podcast/financial-freedom-show",
    spotifyUrl: "https://open.spotify.com/show/financialfreedomshow",
    audienceType: "FIRE Movement & Investors",
    audienceSize: 188,
    estimatedReach: "940K",
    episodeCount: 389,
    matchScore: 79,
    audienceAlignment: 77,
    guestFriendlyScore: 86,
    hostActivity: "weekly",
    guestAcceptance: "open",
    activityStatus: "active",
    visibilityPotential: "very-high",
    badges: ["high-engagement"],
    coverIndex: 5,
    saved: false,
  },
  // ── 31 ─────────────────────────────────────────────────────────
  {
    id: "31",
    name: "The Mindset Lab",
    host: "Dr. Anna Kovacs",
    description: "Applied behavioral science and cognitive psychology for professionals who want evidence-based tools for peak performance.",
    categories: ["Mindset", "Personal Development", "Education"],
    subcategory: "Applied Psychology",
    website: "themindsetlab.com",
    podcastUrl: "https://themindsetlab.com/podcast",
    appleUrl: "https://podcasts.apple.com/podcast/the-mindset-lab",
    spotifyUrl: "https://open.spotify.com/show/mindsetlab",
    audienceType: "Psychology-Curious Professionals",
    audienceSize: 36,
    estimatedReach: "144K",
    episodeCount: 127,
    matchScore: 92,
    audienceAlignment: 90,
    guestFriendlyScore: 89,
    hostActivity: "biweekly",
    guestAcceptance: "open",
    activityStatus: "active",
    visibilityPotential: "medium",
    badges: ["ai-recommended"],
    coverIndex: 0,
    saved: false,
  },
  // ── 32 ─────────────────────────────────────────────────────────
  {
    id: "32",
    name: "Rewired for Success",
    host: "Dr. Jason Webb",
    description: "Neuroplasticity, habit architecture, and the brain science behind transforming your professional performance.",
    categories: ["Mindset", "Health & Wellness"],
    subcategory: "Neuroscience & Performance",
    website: "rewiredpod.com",
    podcastUrl: "https://rewiredpod.com/listen",
    appleUrl: "https://podcasts.apple.com/podcast/rewired-for-success",
    spotifyUrl: "https://open.spotify.com/show/rewiredforsuccess",
    audienceType: "Performance-Focused Professionals",
    audienceSize: 42,
    estimatedReach: "168K",
    episodeCount: 156,
    matchScore: 93,
    audienceAlignment: 91,
    guestFriendlyScore: 84,
    hostActivity: "weekly",
    guestAcceptance: "open",
    activityStatus: "active",
    visibilityPotential: "medium",
    badges: ["ai-recommended", "high-engagement"],
    coverIndex: 1,
    saved: false,
  },
  // ── 33 ─────────────────────────────────────────────────────────
  {
    id: "33",
    name: "The Learning Advantage",
    host: "Prof. Sarah O'Neill",
    description: "How to learn faster, retain more, and apply knowledge strategically in your career and life.",
    categories: ["Education", "Personal Development"],
    subcategory: "Accelerated Learning",
    website: "thelearningadvantage.fm",
    podcastUrl: "https://thelearningadvantage.fm/listen",
    appleUrl: "https://podcasts.apple.com/podcast/learning-advantage",
    spotifyUrl: "https://open.spotify.com/show/learningadvantage",
    audienceType: "Lifelong Learners & Students",
    audienceSize: 53,
    estimatedReach: "265K",
    episodeCount: 198,
    matchScore: 82,
    audienceAlignment: 80,
    guestFriendlyScore: 87,
    hostActivity: "weekly",
    guestAcceptance: "open",
    activityStatus: "active",
    visibilityPotential: "medium",
    badges: [],
    coverIndex: 2,
    saved: false,
  },
  // ── 34 ─────────────────────────────────────────────────────────
  {
    id: "34",
    name: "Teach to Thrive",
    host: "Marcus Johnson",
    description: "The intersection of education, entrepreneurship, and community impact — for educators building something bigger.",
    categories: ["Education", "Entrepreneurship"],
    subcategory: "Edupreneurship",
    website: "teachtothrive.co",
    podcastUrl: "https://teachtothrive.co/podcast",
    appleUrl: "https://podcasts.apple.com/podcast/teach-to-thrive",
    spotifyUrl: "https://open.spotify.com/show/teachtothrive",
    audienceType: "Educator-Entrepreneurs",
    audienceSize: 14,
    estimatedReach: "56K",
    episodeCount: 67,
    matchScore: 78,
    audienceAlignment: 76,
    guestFriendlyScore: 92,
    hostActivity: "biweekly",
    guestAcceptance: "open",
    activityStatus: "active",
    visibilityPotential: "growing",
    badges: ["fast-growing"],
    coverIndex: 3,
    saved: false,
  },
  // ── 35 ─────────────────────────────────────────────────────────
  {
    id: "35",
    name: "The Bold CEO",
    host: "Jennifer Park",
    description: "Women in the C-suite sharing the unspoken realities of founding, funding, and leading at the highest level.",
    categories: ["Women in Business", "Leadership", "Entrepreneurship"],
    subcategory: "Female CEO Stories",
    website: "theboldceo.com",
    podcastUrl: "https://theboldceo.com/listen",
    appleUrl: "https://podcasts.apple.com/podcast/the-bold-ceo",
    spotifyUrl: "https://open.spotify.com/show/theboldceo",
    audienceType: "Women Founders & Executives",
    audienceSize: 89,
    estimatedReach: "445K",
    episodeCount: 243,
    matchScore: 90,
    audienceAlignment: 88,
    guestFriendlyScore: 91,
    hostActivity: "weekly",
    guestAcceptance: "open",
    activityStatus: "active",
    visibilityPotential: "high",
    badges: ["trending", "ai-recommended"],
    coverIndex: 4,
    saved: false,
  },
  // ── 36 ─────────────────────────────────────────────────────────
  {
    id: "36",
    name: "Female Founder Files",
    host: "Alexis Morgan",
    description: "Honest, raw conversations with women who built companies from nothing — the wins, the losses, and the lessons.",
    categories: ["Women in Business", "Entrepreneurship"],
    subcategory: "Female Founders",
    website: "femalefounderfiles.com",
    podcastUrl: "https://femalefounderfiles.com/podcast",
    appleUrl: "https://podcasts.apple.com/podcast/female-founder-files",
    spotifyUrl: "https://open.spotify.com/show/femalefounderfiles",
    audienceType: "Women Entrepreneurs & Aspiring Founders",
    audienceSize: 66,
    estimatedReach: "330K",
    episodeCount: 178,
    matchScore: 88,
    audienceAlignment: 86,
    guestFriendlyScore: 93,
    hostActivity: "biweekly",
    guestAcceptance: "open",
    activityStatus: "active",
    visibilityPotential: "high",
    badges: ["high-engagement"],
    coverIndex: 5,
    saved: false,
  },
  // ── 37 ─────────────────────────────────────────────────────────
  {
    id: "37",
    name: "Changing the Narrative",
    host: "Dr. Keisha Brown",
    description: "Diversity, equity, and systemic change through the lens of business, culture, and courageous leadership.",
    categories: ["Society & Culture", "Leadership"],
    subcategory: "DEI & Social Impact",
    website: "changingnarrative.fm",
    podcastUrl: "https://changingnarrative.fm/listen",
    appleUrl: "https://podcasts.apple.com/podcast/changing-the-narrative",
    spotifyUrl: "https://open.spotify.com/show/changingnarrative",
    audienceType: "DEI-Focused Leaders & Advocates",
    audienceSize: 71,
    estimatedReach: "355K",
    episodeCount: 189,
    matchScore: 83,
    audienceAlignment: 81,
    guestFriendlyScore: 88,
    hostActivity: "weekly",
    guestAcceptance: "open",
    activityStatus: "active",
    visibilityPotential: "medium",
    badges: ["trending"],
    coverIndex: 0,
    saved: false,
  },
  // ── 38 ─────────────────────────────────────────────────────────
  {
    id: "38",
    name: "Science of Success",
    host: "Dr. Thomas Wright",
    description: "Translating cutting-edge research on productivity, decision-making, and human performance into practical business insight.",
    categories: ["Science", "Personal Development", "Education"],
    subcategory: "Applied Research",
    website: "scienceofsuccess.co",
    podcastUrl: "https://scienceofsuccess.co/podcast",
    appleUrl: "https://podcasts.apple.com/podcast/science-of-success",
    spotifyUrl: "https://open.spotify.com/show/scienceofsuccess",
    audienceType: "Research-Curious Professionals",
    audienceSize: 82,
    estimatedReach: "410K",
    episodeCount: 302,
    matchScore: 86,
    audienceAlignment: 84,
    guestFriendlyScore: 81,
    hostActivity: "biweekly",
    guestAcceptance: "selective",
    activityStatus: "hiatus",
    visibilityPotential: "medium",
    badges: ["high-engagement"],
    coverIndex: 1,
    saved: false,
  },
  // ── 39 ─────────────────────────────────────────────────────────
  {
    id: "39",
    name: "Peak Performance Podcast",
    host: "Coach Miguel Santos",
    description: "Elite athlete mindset applied to business — training philosophy, competitive psychology, and the will to win.",
    categories: ["Sports & Performance", "Mindset", "Personal Development"],
    subcategory: "Athletic Mindset",
    website: "peakperformancepod.com",
    podcastUrl: "https://peakperformancepod.com/listen",
    appleUrl: "https://podcasts.apple.com/podcast/peak-performance",
    spotifyUrl: "https://open.spotify.com/show/peakperformance",
    audienceType: "Athletes & Performance Professionals",
    audienceSize: 48,
    estimatedReach: "240K",
    episodeCount: 134,
    matchScore: 81,
    audienceAlignment: 79,
    guestFriendlyScore: 90,
    hostActivity: "weekly",
    guestAcceptance: "open",
    activityStatus: "active",
    visibilityPotential: "growing",
    badges: ["fast-growing"],
    coverIndex: 2,
    saved: false,
  },
  // ── 40 ─────────────────────────────────────────────────────────
  {
    id: "40",
    name: "The Conscious Parent",
    host: "Dr. Lisa Hammond",
    description: "Raising high-character children while pursuing a thriving career — parenting philosophy for ambitious families.",
    categories: ["Parenting", "Personal Development"],
    subcategory: "Conscious Parenting",
    website: "consciousparentpod.com",
    podcastUrl: "https://consciousparentpod.com/listen",
    appleUrl: "https://podcasts.apple.com/podcast/the-conscious-parent",
    spotifyUrl: "https://open.spotify.com/show/consciousparent",
    audienceType: "Parent-Professionals & Families",
    audienceSize: 33,
    estimatedReach: "132K",
    episodeCount: 109,
    matchScore: 77,
    audienceAlignment: 75,
    guestFriendlyScore: 93,
    hostActivity: "biweekly",
    guestAcceptance: "open",
    activityStatus: "hiatus",
    visibilityPotential: "growing",
    badges: [],
    coverIndex: 3,
    saved: false,
  },
]
