"use client"

import { useState, useEffect } from "react"
import { motion } from "motion/react"
import { FileText, Copy, Check, Globe, Mic2, Target, Users, Sparkles } from "lucide-react"
import { getSettings } from "@/lib/actions/settings"
import type { GeneratedProfile } from "@/lib/profile/generate-profile"
import { cn } from "@/lib/utils"

interface Props { profile: GeneratedProfile }

export function MediaKit({ profile }: Props) {
  const [website, setWebsite] = useState("")
  const [copied,  setCopied]  = useState(false)

  useEffect(() => {
    getSettings().then(r => {
      const w = r.data?.profile_settings?.website
      if (typeof w === "string" && w) setWebsite(w)
    }).catch(() => {})
  }, [])

  function buildTextKit() {
    const lines = [
      `== MEDIA KIT — ${profile.title} ==`,
      "",
      `ARCHETYPE: ${profile.creatorArchetype}`,
      `CATEGORY:  ${profile.category}`,
      website ? `WEBSITE:   ${website}` : "",
      "",
      "POSITIONING",
      profile.creatorPositioning,
      "",
      "CORE MESSAGE",
      profile.coreMessage,
      "",
      "PRIMARY EXPERTISE",
      profile.primaryExpertise,
      "",
      "AUDIENCE SERVED",
      profile.audienceServed,
      "",
      "SPEAKING TOPICS",
      profile.speakingTopics.map((t, i) => `  ${i + 1}. ${t}`).join("\n"),
      "",
      `VISIBILITY SCORE:   ${profile.visibilityScore}/100`,
      `AI ALIGNMENT:       ${profile.aiAlignmentScore}/100`,
      "",
      "— Generated by PodcastMatch AI",
    ].filter(l => l !== null).join("\n")
    return lines
  }

  async function handleCopy() {
    try {
      await navigator.clipboard.writeText(buildTextKit())
      setCopied(true)
      setTimeout(() => setCopied(false), 2500)
    } catch {
      /* clipboard not available */
    }
  }

  const scoreColor = (s: number) =>
    s >= 80 ? "text-[var(--premium-gold)]" : s >= 70 ? "text-primary" : "text-[var(--premium-cyan)]"

  return (
    <motion.div
      initial={{ opacity: 0, y: 10 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.4, delay: 0.35 }}
      className="relative rounded-2xl border border-border/60 bg-card/70 backdrop-blur-sm shadow-[var(--shadow-card)] overflow-hidden"
    >
      <div className="absolute inset-x-0 top-0 h-px bg-gradient-to-r from-transparent via-premium-gold/30 to-transparent" />

      <div className="p-6 md:p-8">

        {/* Header */}
        <div className="flex items-center justify-between mb-6">
          <div className="flex items-center gap-2.5">
            <div className="flex items-center justify-center w-8 h-8 rounded-lg bg-[oklch(0.78_0.15_83/0.12)] border border-[oklch(0.78_0.15_83/0.25)]">
              <FileText className="w-4 h-4 text-premium-gold" />
            </div>
            <div>
              <h2 className="text-sm font-bold text-foreground">Media Kit</h2>
              <p className="text-xs text-muted-foreground">Your shareable profile for podcast hosts</p>
            </div>
          </div>
          <button
            onClick={handleCopy}
            className={cn(
              "flex items-center gap-1.5 px-3.5 py-1.5 rounded-lg text-xs font-semibold transition-all duration-200",
              copied
                ? "bg-[oklch(0.55_0.16_145/0.15)] border border-[oklch(0.55_0.16_145/0.30)] text-[oklch(0.70_0.16_145)]"
                : "bg-[oklch(0.78_0.15_83/0.10)] border border-[oklch(0.78_0.15_83/0.25)] text-premium-gold hover:bg-[oklch(0.78_0.15_83/0.18)]"
            )}
          >
            {copied ? <Check className="w-3 h-3" /> : <Copy className="w-3 h-3" />}
            {copied ? "Copied!" : "Copy Kit"}
          </button>
        </div>

        {/* Kit card */}
        <div className="rounded-xl border border-border/40 bg-muted/20 divide-y divide-border/30 overflow-hidden">

          {/* Identity row */}
          <div className="p-4 flex flex-wrap items-start gap-4">
            <div className="flex h-12 w-12 shrink-0 items-center justify-center rounded-xl bg-primary/10 border border-primary/20">
              <Sparkles className="w-6 h-6 text-primary" />
            </div>
            <div className="flex-1 min-w-0">
              <p className="text-sm font-bold text-foreground leading-snug">{profile.title}</p>
              <p className="text-xs text-muted-foreground mt-0.5">{profile.creatorArchetype} · {profile.category}</p>
              {website && (
                <a
                  href={website.startsWith("http") ? website : `https://${website}`}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="inline-flex items-center gap-1 mt-1 text-xs text-primary hover:underline"
                >
                  <Globe className="w-3 h-3" /> {website.replace(/^https?:\/\//, "")}
                </a>
              )}
              {!website && (
                <a href="#section-bio" className="inline-flex items-center gap-1 mt-1 text-xs text-muted-foreground hover:text-primary transition-colors">
                  <Globe className="w-3 h-3" /> Add your website ↑
                </a>
              )}
            </div>
            <div className="flex items-center gap-4 shrink-0">
              <div className="text-center">
                <p className={cn("text-lg font-bold", scoreColor(profile.visibilityScore))}>{profile.visibilityScore}</p>
                <p className="text-[9px] text-muted-foreground uppercase tracking-wide">Visibility</p>
              </div>
              <div className="text-center">
                <p className={cn("text-lg font-bold", scoreColor(profile.aiAlignmentScore))}>{profile.aiAlignmentScore}</p>
                <p className="text-[9px] text-muted-foreground uppercase tracking-wide">AI Align</p>
              </div>
            </div>
          </div>

          {/* Positioning */}
          <div className="p-4 flex gap-3">
            <Target className="w-4 h-4 text-[var(--premium-cyan)] shrink-0 mt-0.5" />
            <div>
              <p className="text-[10px] font-semibold text-muted-foreground uppercase tracking-wider mb-1">Positioning</p>
              <p className="text-sm text-foreground/90 leading-relaxed">{profile.creatorPositioning}</p>
            </div>
          </div>

          {/* Core message */}
          <div className="p-4 flex gap-3">
            <Mic2 className="w-4 h-4 text-primary shrink-0 mt-0.5" />
            <div>
              <p className="text-[10px] font-semibold text-muted-foreground uppercase tracking-wider mb-1">Core Message</p>
              <p className="text-sm text-foreground/90 leading-relaxed">{profile.coreMessage}</p>
            </div>
          </div>

          {/* Audience */}
          <div className="p-4 flex gap-3">
            <Users className="w-4 h-4 text-[var(--premium-gold)] shrink-0 mt-0.5" />
            <div>
              <p className="text-[10px] font-semibold text-muted-foreground uppercase tracking-wider mb-1">Audience Served</p>
              <p className="text-sm text-foreground/90 leading-relaxed">{profile.audienceServed}</p>
            </div>
          </div>

          {/* Speaking topics */}
          <div className="p-4">
            <p className="text-[10px] font-semibold text-muted-foreground uppercase tracking-wider mb-2.5">Speaking Topics</p>
            <div className="flex flex-wrap gap-2">
              {profile.speakingTopics.map(topic => (
                <span
                  key={topic}
                  className="px-3 py-1.5 rounded-full text-xs font-semibold border border-primary/25 bg-primary/8 text-primary"
                >
                  {topic}
                </span>
              ))}
            </div>
          </div>

        </div>

        {!website && (
          <p className="mt-3 text-xs text-muted-foreground/60 text-center">
            💡 Add your website above to complete your media kit
          </p>
        )}
      </div>
    </motion.div>
  )
}
